<?php

namespace Main\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
	public function getCategories()
	{
		$qb = $this->createQueryBuilder('c')
				   ->select('c');

		return $qb->getQuery()
                  ->getResult();
	}
}
