main_main_homepage:
    pattern:  /
    defaults: { _controller: MainMainBundle:Page:index }
main_main_login:
    pattern: /login
    defaults: {_controller: MainMainBundle:Security:login}
main_main_login_check:
    pattern: /login_check
main_main_logout:
    pattern: /logout
main_main_products:
    pattern:  /products/{category}/{page}
    defaults: { _controller: MainMainBundle:Products:prods, category: 1, page: 1 }
main_main_products_list:
    pattern:  /products_list/{category}/{page}
    defaults: { _controller: MainMainBundle:Products:list, category: 1, page:1 }
main_main_search:
    pattern:  /search/{page}
    defaults: { _controller: MainMainBundle:Products:search, page: 1 }
main_main_search_list:
    pattern:  /search_list/{page}
    defaults: { _controller: MainMainBundle:Products:searchList, page: 1 }
main_main_product_detail:
    pattern: /product_detail/{product_id}
    defaults: { _controller: MainMainBundle:Products:productDetail }
main_main_calendar:
    pattern: /calendar
    defaults: { _controller: MainMainBundle:Products:calendar }
main_main_register:
    pattern: /register
    defaults: {_controller: MainMainBundle:Security:register}