parameters:
    main_main.products.class: Main\MainBundle\Service\ProductsService

services:
   main_main.products:
       class: %main_main.products.class%
       arguments: [@request, %main_main.filter.percent_step%]
       public: true
       scope: request
   main_main.twig.extension:
        class: Main\MainBundle\Twig\Extensions\MainMainBundleExtension
        tags:
            - { name: twig.extension }