parameters:
#    main_main.example.class: Main\MainBundle\Example

services:
#    main_main.example:
#        class: %main_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    main_main.twig.extension:
        class: Main\MainBundle\Twig\Extensions\MainMainBundleExtension
        tags:
            - { name: twig.extension }